package com.github.zero9178.mlirods.integration

import com.github.zero9178.mlirods.model.COMPILE_COMMANDS_FILE_NAME
import com.github.zero9178.mlirods.model.CompilationCommandsState
import com.github.zero9178.mlirods.model.IncludePaths
import com.github.zero9178.mlirods.model.TableGenCompilationCommandsProvider
import com.github.zero9178.mlirods.model.readCompilationCommands
import com.intellij.openapi.project.Project
import com.intellij.openapi.vfs.LocalFileSystem
import com.intellij.openapi.vfs.VirtualFile
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.flowOn
import kotlin.io.path.Path
import kotlin.io.path.inputStream

/**
 * Provides the compilation commands found in the file [COMPILE_COMMANDS_FILE_NAME] at the root of a project.
 *
 * The file is the one generated by LLVM's CMake, except that all its paths are relative to the root of the project.
 * This makes a project self-contained: it requires neither CMake, nor a C++ toolchain, nor CLion to have contexts for
 * its TableGen files. See 'updateLLVMMirror.py' for how such a project is created.
 */
class ProjectFileCompilationCommandsProvider : TableGenCompilationCommandsProvider {

    override fun getCompilationCommandsFlow(project: Project): Flow<CompilationCommandsState> = flow {
        val root = Path(project.basePath!!)
        val fileSystem = LocalFileSystem.getInstance()
        // Most include paths are shared by many commands.
        val cache = HashMap<String, VirtualFile?>()
        fun find(path: String) = cache.getOrPut(path) { fileSystem.refreshAndFindFileByNioFile(root.resolve(path)) }

        val commands = root.resolve(COMPILE_COMMANDS_FILE_NAME).inputStream().use { readCompilationCommands(it) }
        // Later commands of a file replace earlier ones as with the commands CMake generated.
        emit(CompilationCommandsState(commands.mapNotNull { command ->
            find(command.filepath)?.let { it to IncludePaths(command.includes.split(';').mapNotNull(::find)) }
        }.toMap()))
    }.flowOn(Dispatchers.IO)
}
