{
  parserClass="com.github.zero9178.mlirods.language.generated.TableGenParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="TableGen"
  psiImplClassSuffix="Impl"
  psiPackage="com.github.zero9178.mlirods.language.generated.psi"
  psiImplPackage="com.github.zero9178.mlirods.language.generated.psi.impl"
  psiImplUtilClass="com.github.zero9178.mlirods.language.psi.impl.TableGenPsiImplUtil"

  generate=[exact-types="all" visitor="no"]
  elementTypeHolderClass="com.github.zero9178.mlirods.language.generated.TableGenTypes"
  elementTypeClass="com.github.zero9178.mlirods.language.TableGenElementType"
  tokenTypeClass="com.github.zero9178.mlirods.language.TableGenTokenType"
  tokens = [
    PLUS='+'
    MINUS='-'
    LBRACKET='['
    RBRACKET=']'
    LBRACE='{'
    RBRACE='}'
    LANGLE='<'
    RANGLE='>'
    LPAREN='('
    RPAREN=')'
    COMMA=','
    COLON=':'
    SEMICOLON=';'
    DOT='.'
    ELLIPSE='...'
    EQUALS='='
    QUESTION_MARK='?'
    HASHTAG='#'
    ASSERT='assert'
    BIT='bit'
    BITS='bits'
    CLASS='class'
    CODE='code'
    DAG='dag'
    DEF='def'
    DUMP='dump'
    ELSE='else'
    FALSE='false'
    FOREACH='foreach'
    DEFM='defm'
    DEFSET='defset'
    DEFTYPE='deftype'
    DEFVAR='defvar'
    FIELD='field'
    IF='if'
    IN='in'
    INCLUDE='include'
    INT='int'
    LET='let'
    LIST='list'
    MULTICLASS='multiclass'
    STRING='string'
    THEN='then'
    TRUE='true'
    HASHTAG_DEFINE='#define'
    HASHTAG_IFDEF='#ifdef'
    HASHTAG_IFNDEF='#ifndef'
    HASHTAG_ELSE='#else'
    HASHTAG_ENDIF='#endif'
    IDENTIFIER="regexp:[0-9]*[a-zA-Z_][a-zA-Z_0-9]*"
    VAR_IDENTIFIER="regexp:\$[a-zA-Z_][a-zA-Z_0-9]*"
    INTEGER="regexp:(([+\-])?[0-9]+)|(0x[0-9a-fA-F]+)|(0b[01]+)"
    BANG_OPERATOR="regexp:![a-zA-Z]+"
    BANG_COND="!cond"
    BANG_FOREACH="!foreach"
    BANG_FOLDL="!foldl"
    // Used by live preview only.
    WHITE_SPACE="regexp:\s*"
  ]

  extends(".*_type_node")=type_node
  implements(".*_body_item")=scope_item
  implements(".*_statement")=scope_item
  extends(".*_value")=value
}

tableGenFile ::= table_gen_file_item*
// For error recovery purposes, assume the user meant to write a statement and pin that choice to parse the entire file.
private table_gen_file_item ::= (include_directive | table_gen_file_item_statement)
private table_gen_file_item_statement ::= !<<eof>> statement {
    pin=1
}

// Fake base class referring to either body items or statements. Guaranteed to have a [TableGenIdentifierScopeNode] as
// parent, which is said to be the scope it is contained in.
fake scope_item ::= {
    implements=[
        "com.github.zero9178.mlirods.language.psi.impl.TableGenScopeItemEx"
    ]
}

private statement ::= assert_statement
                | class_statement
                | def_statement
                | defm_statement
                | defset_statement
                | deftype_statement
                | defvar_statement
                | dump_statement
                | foreach_statement
                | if_statement
                | let_statement
                | multiclass_statement
                | others_statement {
    recoverWhile=statement_recover
}
private statement_recover ::= !(statement_follows)
private statement_follows ::= 'def' | 'include' | 'class' | 'defm' | 'defset' | 'defvar' | 'dump' | 'foreach'
                            | 'if' | 'let' | 'multiclass' | 'assert' | '}' | 'else'

others_statement ::= BLOCK_COMMENT
                   | LINE_COMMENT
                   | OTHER

include_directive ::= 'include' LINE_STRING_LITERAL {
    pin=1
    methods=[
        string="LINE_STRING_LITERAL"

        toString
    ]
    implements=["com.github.zero9178.mlirods.language.psi.impl.TableGenIncludeDirectiveEx"]
    stubClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenIncludeDirectiveStub"
    mixin="com.github.zero9178.mlirods.language.psi.impl.TableGenIncludeDirectiveMixin"
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenIncludeDirectiveStubElementType"
}
//noinspection BnfUnusedRule
preprocessor_directive ::= define_directive
                         | ifdef_ifndef_directive
                         | else_directive
                         | endif_directive

//noinspection BnfUnusedRule
skipped_code_block ::=

define_directive ::= '#define' IDENTIFIER {
    extends=preprocessor_directive
    pin=1
}

ifdef_ifndef_directive ::= ('#ifdef' | '#ifndef') IDENTIFIER {
    extends=preprocessor_directive
    pin=1
}

else_directive ::= '#else' {
    extends=preprocessor_directive
}

endif_directive ::= '#endif' {
    extends=preprocessor_directive
}

assert_statement ::= 'assert' value ',' value ';' {pin=1}

private equals_value ::= '=' value {pin=1}

// Fake base class for elements common among 'class' and 'multiclass' statements.
fake abstract_class_statement ::= template_arg_list? parent_class_list? '{'? '}'? {
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenFoldingElement"
        "com.github.zero9178.mlirods.language.psi.TableGenIdentifierScopeNode"
    ]
    methods = [
        lAngle='LANGLE'
        rAngle='RANGLE'
        lBrace='LBRACE'
        rBrace='RBRACE'

        getPlaceHolderText
        getFoldingTextRanges
    ]
}

class_statement ::= 'class' IDENTIFIER template_arg_list? record_body {
    methods = [
        lAngle='LANGLE'
        rAngle='RANGLE'
        lBrace='LBRACE'
        rBrace='RBRACE'

        toString
        getPlaceHolderText
        getFoldingTextRanges
        getPresentation
    ]
    implements=[
        abstract_class_statement
        scope_item

        "com.intellij.navigation.NavigationItem"
        "com.intellij.psi.PsiNameIdentifierOwner"
        "com.github.zero9178.mlirods.language.psi.TableGenFieldScopeNode"
    ]
    stubClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenClassStatementStub"
    mixin="com.github.zero9178.mlirods.language.psi.impl.TableGenClassStatementMixin"
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenClassStatementStubElementType"
    pin=1
}
private template_arg_list ::= '<' template_arg_decl (',' template_arg_decl)* '>' {pin(".*")=1}
template_arg_decl ::= type_node IDENTIFIER equals_value? {
    pin=1
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenDefNameIdentifierOwner"
    ]
    methods=[
        nameIdentifier='IDENTIFIER'

        getName
        setName
        getTextOffset
    ]
}
private record_body ::= parent_class_list? body {pin=1}
private parent_class_list ::= ':' class_ref (',' class_ref)* {pin=1}

fake abstract_class_ref ::= IDENTIFIER {
    methods=[
        class_identifier='IDENTIFIER'

        getClassName
    ]
    implements=[
        "com.github.zero9178.mlirods.language.psi.impl.TableGenAbstractClassRefEx"
    ]
}

class_ref ::= IDENTIFIER class_ref_suffix? {
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenAngledFoldingElement"
        abstract_class_ref
    ]
    methods = [
        lAngle='LANGLE'
        rAngle='RANGLE'
        class_identifier='IDENTIFIER'

        toString
        getClassName
        getReference
    ]
    stubClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenClassRefStub"
    mixin="com.github.zero9178.mlirods.language.psi.impl.TableGenClassRefMixin"
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenClassRefStubElementType"
}
private class_ref_suffix ::= '<' arg_value_list? '>' {pin=1}
private body ::= ';' | body_list
private body_list ::= '{' body_item* '}' {pin=1}

private body_recover ::= !('}' | 'field' | 'let' | 'defvar' | 'assert' | 'bit' | 'bits' | 'code' | 'dag' | 'int'
                       | 'list' | 'string' | IDENTIFIER)

private body_item ::= field_body_item
                    | let_body_item
                    | defvar_statement
                    | assert_statement
                    {recoverWhile=body_recover}
field_body_item ::= 'field'? type_node IDENTIFIER equals_value? ';' {
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenFieldIdentifierNode"

        "com.intellij.navigation.NavigationItem"
        "com.intellij.psi.PsiNameIdentifierOwner"
    ]
    methods=[
        field_identifier="IDENTIFIER"

        toString
        getPresentation
    ]
    stubClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenFieldBodyItemStub"
    mixin="com.github.zero9178.mlirods.language.psi.impl.TableGenFieldBodyItemMixin"
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenFieldBodyItemStubElementType"
    pin=2
}
let_body_item ::= 'let' IDENTIFIER ('{' range_list '}')? '=' value ';' {
    pin=1
    implements="com.github.zero9178.mlirods.language.psi.TableGenFieldIdentifierNode"
    methods=[
        field_identifier="IDENTIFIER"

        getReference
    ]
}

def_statement ::= 'def' value? record_body {
    pin=1
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenBracedFoldingElement"
        "com.github.zero9178.mlirods.language.psi.TableGenDefNameIdentifierOwner"
        "com.github.zero9178.mlirods.language.psi.TableGenFieldScopeNode"
        scope_item
    ]
    methods=[
        lBrace='LBRACE'
        rBrace='RBRACE'

        toString
        getName
        setName
        getTextOffset
        getPresentation
    ]
    stubClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenDefNameIdentifierStub"
    mixin="com.github.zero9178.mlirods.language.psi.impl.TableGenDefStatementMixin"
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenDefNameIdentifierStubElementType"
}
defm_statement ::= 'defm' value? parent_class_list? ';' {pin=1}
defset_statement ::= 'defset' type_node IDENTIFIER '=' '{' statement* '}' {pin=1}
deftype_statement ::= 'deftype' IDENTIFIER '=' type_node ';' {pin=1}
defvar_statement ::= 'defvar' IDENTIFIER '=' value ';' {
    pin=1
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenDefNameIdentifierOwner"
        scope_item
    ]
    methods=[
        nameIdentifier='IDENTIFIER'

        toString
        getName
        setName
        getTextOffset
        getPresentation
    ]
    stubClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenDefNameIdentifierStub"
    mixin="com.github.zero9178.mlirods.language.psi.impl.TableGenDefvarStatementMixin"
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenDefNameIdentifierStubElementType"
}
dump_statement ::= 'dump' value ';' {pin=1}

private statement_block ::= statement_block_list | statement
private statement_block_list ::= '{' statement* '}' {pin=1}

foreach_statement ::= 'foreach' foreach_iterator 'in' statement_block {
    pin=1
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenBracedFoldingElement"
        "com.github.zero9178.mlirods.language.psi.TableGenIdentifierScopeNode"
    ]
    methods = [
        lBrace='LBRACE'
        rBrace='RBRACE'
    ]
}
foreach_iterator ::= IDENTIFIER '=' ('{' range_list '}' | range_piece | value)

if_statement ::= 'if' value 'then' if_body else_body? {
    methods=[
        thenBody="if_body[0]"
        elseBody="if_body[1]"
    ]
    pin=1
}
private else_body ::= 'else' if_body {pin=1}
if_body ::= statement_block {
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenBracedFoldingElement"
        "com.github.zero9178.mlirods.language.psi.TableGenIdentifierScopeNode"
    ]
    methods = [
        lBrace='LBRACE'
        rBrace='RBRACE'
    ]
}

let_statement ::= 'let' let_list 'in' statement_block {
    pin=1
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenBracedFoldingElement"
        "com.github.zero9178.mlirods.language.psi.TableGenIdentifierScopeNode"
    ]
    methods = [
        lBrace='LBRACE'
        rBrace='RBRACE'
    ]
}
private let_list ::= let_item (',' let_item)*
let_item ::= IDENTIFIER ('<' range_list '>')? '=' value {
    implements="com.github.zero9178.mlirods.language.psi.TableGenFieldIdentifierNode"
    methods=[
        field_identifier="IDENTIFIER"
    ]
}
multiclass_statement ::= 'multiclass' IDENTIFIER template_arg_list? parent_class_list? (';' | statement_block) {
    methods = [
        lAngle='LANGLE'
        rAngle='RANGLE'
        lBrace='LBRACE'
        rBrace='RBRACE'

        getPlaceHolderText
        getFoldingTextRanges
    ]
    implements=abstract_class_statement
    pin=1
}

type_node ::= bit_type_node
          | int_type_node
          | string_type_node
          | dag_type_node
          | code_type_node
          | bits_type_node
          | list_type_node
          | class_type_node {
    implements=[
        "com.github.zero9178.mlirods.language.psi.impl.TableGenTypeNodeEx"
    ]
    methods=[
        toString
    ]
    stubClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenTypeNodeStub"
    mixin="com.github.zero9178.mlirods.language.psi.impl.TableGenTypeNodeMixin"
}
bit_type_node ::= 'bit' {
    methods=[
        toType
    ]
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenBitTypeNodeStubElementType"
}
int_type_node ::= 'int' {
    methods=[
        toType
    ]
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenIntTypeNodeStubElementType"
}
string_type_node ::= 'string' {
    methods=[
        toType
    ]
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenStringTypeNodeStubElementType"
}
dag_type_node ::= 'dag' {
    methods=[
        toType
    ]
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenDagTypeNodeStubElementType"
}
code_type_node ::= 'code' {
    methods=[
        toType
    ]
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenCodeTypeNodeStubElementType"
}
bits_type_node ::= 'bits' '<' INTEGER '>' {
    pin=1
    methods=[
        toType
    ]
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenBitsTypeNodeStubElementType"
}
list_type_node ::= 'list' '<' type_node '>' {
    pin=1
    methods=[
        toType
    ]
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenListTypeNodeStubElementType"
}
class_type_node ::= IDENTIFIER {
    methods=[
        class_identifier='IDENTIFIER'

        getClassName
        getReference
        toType
    ]
    implements=abstract_class_ref
    elementTypeClass="com.github.zero9178.mlirods.language.stubs.impl.TableGenClassTypeNodeStubElementType"
}

value ::= concat_value
        | field_access_value
        | bit_access_value
        | slice_access_value
        | simple_value {
    implements=[
        "com.github.zero9178.mlirods.language.psi.impl.TableGenValueEx"
    ]
}
private value_follows ::= '#' | '[' | '{' | 'then' | 'in' | '.' | ',' | ':' | '=' | ')' | ']' | '}' | ';' | '>'

concat_value ::= value '#' value? {
    pin=2
    methods = [
        left_operand="/value[0]"
        right_operand="/value[1]"

        getType
    ]
}
field_access_value ::= value '.' IDENTIFIER {
    implements="com.github.zero9178.mlirods.language.psi.TableGenFieldIdentifierNode"
    methods = [
        field_identifier="IDENTIFIER"

        getReference
        getType
    ]
    pin=2
}

bit_access_value ::= value '{' range_list '}' {pin=2}
private range_list ::= range_piece (',' range_piece)*
range_piece ::= bit_range
              | single_bit
single_bit ::= INTEGER {extends=range_piece}
bit_range ::= INTEGER ('...' | '-')? INTEGER {
    extends=range_piece
}

slice_access_value ::= value '[' slice_element (',' slice_element)* ']' {
    pin=2
    methods=[
        getType
    ]
}
slice_element ::= slice_element_range
                | single_slice_element
single_slice_element ::= value {extends=slice_element}
slice_element_range ::= value ((('...' | '-') value) | INTEGER) {extends=slice_element}

private simple_value ::= integer_value
               | string_value
               | bool_value
               | undef_value
               | bits_init_value
               | list_init_value
               | dag_init_value
               | class_instantiation_value
               | identifier_value
               | cond_operator_value
               | foreach_operator_value
               | foldl_operator_value
               | bang_operator_value

private value_list_ne ::= value (',' value)*

integer_value ::= INTEGER {
    methods=[
        getType
    ]
}
string_value ::= block_string_value
               | LINE_STRING_LITERAL+
               | LINE_STRING_LITERAL_BAD {
    methods=[
        getType
    ]
}
block_string_value ::= BLOCK_STRING_LITERAL {
    extends=string_value
    implements="com.github.zero9178.mlirods.language.psi.TableGenFoldingElement"
    methods = [
        getPlaceHolderText
        getType
    ]
}
bool_value ::= 'true' | 'false' {
    methods=[
        getType
    ]
}
undef_value ::= '?'

bits_init_value ::= '{' value_list_ne? '}' {
    pin=1
}

// Exit early if this is a trailing comma before closing. Otherwise, we assume a value is meant to come after.
// If a value failed to parse we recover by finding either the next comma or a closing square bracket.
private trailing_list_init_value_item ::= !(',' ']') ',' value  {
    pin=2
    recoverWhile=list_init_value_item_recover
}
private list_init_value_item_recover ::= !(']' | ',')
private list_init_value_body ::= value trailing_list_init_value_item* {
    pin=1
}

// Initial rule to first attempt to parse ']' and recover to the first item if not. This effectively implements a
// "assume anything within the square brackets should be a value" error recovery strategy.
// Recovery rule runs regardless of result and must therefore halt if either a value or something in the follow set of
// 'list_init_value' appears.
private list_init_value_closing ::= ']' {
    recoverWhile=list_init_value_closing_recover
}
private list_init_value_closing_recover ::= !('<' | value_follows | value)

list_init_value ::= '[' (list_init_value_closing | list_init_value_body ','? ']') ('<' type_node '>')? {
    pin=1
    methods=[
        getType
    ]
}
dag_init_value ::= '(' dag_arg [dag_arg (',' dag_arg)*] ')' {
    pin=1
    methods=[
        operator="dag_arg[0]"

        getType
    ]
}
dag_arg ::= value (':' VAR_IDENTIFIER)? | VAR_IDENTIFIER
identifier_value ::= IDENTIFIER {
    methods=[
        getReference

        getType
    ]
}

class_instantiation_value ::= IDENTIFIER '<' arg_value_list? '>' {
    pin=2
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenAngledFoldingElement"
        abstract_class_ref
    ]
    methods = [
        lAngle='LANGLE'
        rAngle='RANGLE'
        class_identifier='IDENTIFIER'

        getClassName
        getReference
        getType
    ]
}
// Note: This is a simplification from the official syntax that is easier to parse.
private arg_value_list ::= arg_value_item (',' arg_value_item)*
arg_value_item ::= value equals_value?

foreach_operator_value ::= '!foreach' '(' IDENTIFIER ',' value ',' value ')' {
    pin=1
    methods=[
        iterable="/value[0]"
        body="/value[1]"
        name_identifier="IDENTIFIER"

        getType
        getName
        setName
        getTextOffset
    ]
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenDefNameIdentifierOwner"
    ]
}

foldl_accumulator ::= IDENTIFIER {
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenDefNameIdentifierOwner"
    ]
    methods=[
        name_identifier="IDENTIFIER"

        getName
        setName
        getTextOffset
    ]
}
foldl_operator_value ::= '!foldl' '(' value ',' value ',' foldl_accumulator ',' IDENTIFIER ',' value ')' {
    pin=1
    methods=[
        start="/value[0]"
        iterable="/value[1]"
        body="/value[2]"
        name_identifier="IDENTIFIER"

        getType
        getName
        setName
        getTextOffset
    ]
    implements=[
        "com.github.zero9178.mlirods.language.psi.TableGenDefNameIdentifierOwner"
    ]
}

bang_operator_value ::= BANG_OPERATOR ('<' type_node '>')? '(' value_list_ne ')' {pin=1}
cond_operator_value ::= '!cond' '(' cond_clause (',' cond_clause)* ')' {pin=1}
cond_clause ::= value ':' value {
    methods=[
        condition="value[0]"
        thenValue="value[1]"
    ]
}
